// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddressView: typeof import('./src/components/AddressView.vue')['default']
    CollectionView: typeof import('./src/components/CollectionView.vue')['default']
    Comment: typeof import('./src/components/Comment.vue')['default']
    CountDownView: typeof import('./src/components/CountDownView.vue')['default']
    GoodSelectDialog: typeof import('./src/components/GoodSelectDialog.vue')['default']
    OrderView: typeof import('./src/components/OrderView.vue')['default']
    ProductView: typeof import('./src/components/ProductView.vue')['default']
    ShopCarView: typeof import('./src/components/ShopCarView.vue')['default']
  }
}

export { }
